### ISSUE TITLE
Support for WebdriverIO v3.0

### ISSUE THREAD

**Issue by astoilkov** [webdriverio/webdrivercss#123] opened 2015-10-07 13:06 UTC
I have been seeing the statement in the README that says is still not compatible. I am waiting this for a long time so I figured I should create an issue to push the progress forward and track the status of this. Additionally, anyone who wants the same could +1 this issue.

**Comment by skercher** [comment] 2015-10-07 21:16
+1

**Comment by benurb** [comment] 2015-10-08 07:27
+1
Also see #115

**Comment by astoilkov** [comment] 2015-10-08 07:48
@benurb this is awesome. I am wondering why this isn't still merged.

**Comment by benurb** [comment] 2015-10-08 12:47
Well I guess, because @christian-bromann wants to do it in a more thorough way. My PR only changes the API of WebdriverCSS and calls to Webdriver.io to be compatible with version 3. The already existing branch 1.2 auf WebdriverCSS furthermore changes internal things (like replacing async with q, which is used by wdio 3).

**Comment by mjancarik** [comment] 2015-10-22 12:37
+1

**Comment by kabirsikand** [comment] 2015-10-28 20:42
+1

**Comment by adstage-jason** [comment] 2015-10-28 20:46
+1

**Comment by spinlock99** [comment] 2015-10-28 20:56
:+1:

**Comment by DV3D** [comment] 2015-10-28 21:08
+1

**Comment by gworley3** [comment] 2015-10-28 21:28
+1

**Comment by christian-bromann** [comment] 2015-10-28 22:04
Sorry that this took so long. I just pushed a beta to NPM `webdrivercss@2.0.0-beta-rc1` that has #115 merged. Wasn't able to test this. So please let me know if that works for you.
Thanks!

**Comment by Blackbaud-PatrickOFriel** [comment] 2015-11-05 15:00
Just started playing around with webdrivercss and webdriverio yesterday. The prerelease seems to work for me so far using the latest webdriverio and grunt-webdriver.

**Comment by DV3D** [comment] 2015-11-05 15:11
@christian-bromann your beta-rc1 release is working for me too, thanks you!
Will let you know when I stumble upon something.

**Comment by Blackbaud-PatrickOFriel** [comment] 2015-11-12 15:04
One thing I am finding while using the release candidate is that when using webdrivercss with  browserstack and grunt-webdriver through Travis with a test like below in a few browsers (where selector = '.btn-primary' and screenshotName = 'MAC_chrome_button_primary_hover')

```
browser
   .url('/buttons/fixtures/test.full.html')
    .moveToObject(selector)
     .webdrivercss(('button_' + type + '_hover'), [
      {
             name: screenshotName,
             elem: ('#screenshots-buttons-' + type)
       }
       ], function (err, res) {
           expect(err).toBe(undefined);
           expect(res[screenshotName][0].isWithinMisMatchTolerance).toBe(true);
       })
       .call(done);
```

I will randomly get this error: 
```
/home/travis/build/blackbaud/skyux/node_modules/webdriverio/node_modules/q/q.js:141
                throw e;
                      ^
non_object_property_load: Cannot read property 'MAC_chrome_button_primary_hover' of undefined
    at execute("return !!document.evaluate;") - ensureClientSideSelectorSupport.js:10:17
    at selectorExecute("#screenshots-buttons-primary", <Function>) - getPageInfo.js:94:2
```

It happens on every couple test runs I have. Any ideas about what could be going wrong?

**Comment by AOlefirenko** [comment] 2016-02-21 21:24
+1

**Comment by vpatton** [comment] 2016-03-09 17:26
Any update on this?  I was hoping to use this because webdriverIO has everything else I need, but the css regression is my main focus

**Comment by dnnyz** [comment] 2016-03-10 07:48
Any update on webdrivercss@2.0.0 final release version?

**Comment by shakhal** [comment] 2016-03-14 00:51
+1

**Comment by christian-bromann** [comment] 2016-03-14 00:55
We are getting closer to the website update and updating the plugins is the next step then

**Comment by shakhal** [comment] 2016-03-14 00:58
thank you so much!

**Comment by shakhal** [comment] 2016-03-14 03:08
Can anyone share, what combination of versions for WebdriverIO and WebdriverCSS is the last known to work for them?

**Comment by vpatton** [comment] 2016-03-15 19:52
My company has a 2 day company wide hackathon (we get to work on any projects our little minds desire) and I'd like to be able to present this, sooo no pressure :P

**Comment by talitore** [comment] 2016-04-25 18:01
One issue I found using this the rc1 branch; if the selected element has a height of 0 then both the results and error returned will be `undefined` instead of the previous and expected `{ [Error: [webdrivercss("services",{"name":"services","elem":"#foo","screenWidth":[1280,960,600,400]})] <= 
 Command failed: gm convert: geometry dimensions are zero (unable to crop image).
] code: 1, signal: null }`

**Comment by christian-bromann** [comment] 2016-05-09 22:17
Sorry for my absence in this project. I will start updating it today. Please give me suggestions what we can improve [here](https://github.com/webdriverio/webdrivercss/issues/151).

**Closed by christian-bromann** 2016-05-09 22:17 UTC

**Comment by petrmiko** [comment] 2016-05-12 08:39
What is the eta on 2.0.0, which will support Webdriver 3, please?
